fortunes = [
    "a beautiful, smart, and loving person will be coming into your life",
    "a dubious friend may be an enemy in camouflage",
    "a faithful friend is a strong defense",
    "a feather in the hand is better than a bird in the air.",
    "a fresh start will put you on your way",
    "a friend asks only for your time not your money",
    "a friend is a present you give yourself",
    "a gambler not only will lose what he has, but also will lose what he doesn’t have",
    "a golden egg of opportunity falls into your lap this month",
    "a good friendship is often more important than a passionate romance",
    "a good time to finish up old tasks.",
    "a hunch is creativity trying to tell you something",
    "a lifetime friend shall soon be made",
    "a lifetime of happiness lies ahead of you",
    "a light heart carries you through all the hard times",
    "a new perspective will come with the new year.",
    "a person of words and not deeds is like a garden full of weeds",
    "a pleasant surprise is waiting for you",
    "a short pencil is usually better than a long memory any day",
    "a small donation is call for. it’s the right thing to do",
    "a smile is your personal welcome mat",
    "a smooth long journey! great expectations",
    "a soft voice may be awfully persuasive",
    "a truly rich life contains love and art in abundance",
    "accept something that you cannot change, and you will feel better",
    "adventure can be real happiness",
    "advice is like kissing. it costs nothing and is a pleasant thing to do.",
    "advice, when most needed, is least heeded",
    "all the effort you are making will ultimately pay off",
    "all the troubles you have will pass away very quickly",
    "all will go well with your new project",
    "all your hard work will soon pay off",
    "allow compassion to guide your decisions",
    "an acquaintance of the past will affect you in the near future",
    "an agreeable romance might begin to take on the appearance",
    "an important person will offer you support",
    "an inch of time is an inch of gold",
    "any decision you have to make tomorrow is a good decision",
    "at the touch of love, everyone becomes a poet",
    "be careful or you could fall for some tricks today",
    "beauty in its various forms appeals to you.",
    "because you demand more from yourself, others respect you deeply",
    "believe in yourself and others will too",
    "believe it can be done",
    "better ask twice than lose yourself once",
    "bide your time, for success is near",
    "carve your name on your heart and not on marble",
    "change is happening in your life, so go with the flow",
    "competence like yours is underrated",
    "congratulations! you are on your way",
    "could i get some directions to your heart?",
    "courtesy begins in the home",
    "courtesy is contagious",
    "curiosity kills boredom. nothing can kill curiosity",
    "dedicate yourself with a calm mind to the task at hand",
    "depart not from the path which fate has you assigned",
    "determination is what you need now",
    "diligence and modesty can raise your social status",
    "disbelief destroys the magic",
    "distance yourself from the vain",
    "do not be intimidated by the eloquence of others",
    "do not demand for someone’s soul if you already got his heart",
    "do not let ambitions overshadow small success",
    "do not make extra work for yourself",
    "do not underestimate yourself. human beings have unlimited potentials",
    "do you know that the busiest person has the largest amount of time",
    "don’t be discouraged, because every wrong attempt discarded is another step forward",
    "don’t confuse recklessness with confidence.",
    "don’t just spend time. invest it",
    "don’t just think, act",
    "don’t let friends impose on you, work calmly and silently",
    "don’t let the past and useless detail choke your existence",
    "don’t let your limitations overshadow your talents",
    "don’t worry; prosperity will knock on your door soon",
    "each day, compel yourself to do something you would rather not do",
    "education is the ability to meet life’s situations",
    "embrace this love relationship you have",
    "emulate what you admire in your parents.",
    "emulate what you respect in your friends",
    "every flower blooms in its own sweet time",
    "every wise man started out by asking many questions",
    "everyday in your life is a special occasion",
    "everywhere you choose to go, friendly faces will greet you",
    "expect much of yourself and little of others",
    "failure is the chance to do better next time",
    "failure is the path of lease persistence",
    "fear and desire – two sides of the same coin",
    "fearless courage is the foundation of victory",
    "feeding a cow with roses does not get extra appreciation",
    "first think of what you want to do; then do what you have to do",
    "follow the middle path. neither extreme will make you happy",
    "for hate is never conquered by hate. hate is conquered by love",
    "for the things we have to learn before we can do them, we learn by doing them",
    "fortune not found: abort, retry, ignore",
    "from listening comes wisdom and from speaking repentance",
    "from now on your kindness will lead you to success",
    "get your mind set – confidence will lead you on",
    "get your mind set…confidence will lead you on",
    "go for the gold today! you’ll be the champion of whatever",
    "go take a rest; you deserve it",
    "good news will be brought to you by mail",
    "good news will come to you by mail",
    "good to begin well, better to end well",
    "happiness begins with facing life with a smile and a wink",
    "happiness will bring you good luck",
    "happy life is just in front of you",
    "hard words break no bones, fine words butter no parsnips",
    "have a beautiful day",
    "he who expects no gratitude shall never be disappointed.",
    "he who knows he has enough is rich",
    "he who knows others is wise. he who knows himself is enlightened",
    "help! i’m being held prisoner in a chinese bakery",
    "how many of you believe in psycho-kinesis? raise my hand",
    "how you look depends on where you go",
    "i learn by going where i have to go",
    "if a true sense of value is to be yours it must come through service",
    "if certainty were truth, we would never be wrong",
    "if you continually give, you will continually have",
    "if you look in the right places, you can find some good offerings",
    "if you think you can do a thing or think you can’t do a thing, you’re right",
    "if you wish to see the best in others, show the best of yourself",
    "if your desires are not extravagant, they will be granted",
    "if your desires are not to extravagant they will be granted.",
    "if you’re feeling down, try throwing yourself into your work",
    "imagination rules the world",
    "in order to take, one must first give",
    "in the end all things will be known",
    "in this world of contradiction, it’s [sic] better to be merry than wise",
    "it could be better, but its[sic] good enough",
    "it is better to be an optimist and proven a fool than to be a pessimist and be proven right",
    "it is better to deal with problems before they arise",
    "it is honorable to stand up for what is right, however unpopular it seems",
    "it is worth reviewing some old lessons",
    "it takes courage to admit fault",
    "it’s not the amount of time you devote, but what you devote to the time that counts",
    "it’s time to get moving. your spirits will lift accordingly",
    "keep your face to the sunshine and you will never see shadows",
    "let the world be filled with tranquility and goodwill",
    "like the river flow into the sea. something are just meant to be",
    "listen not to vain words of empty tongue",
    "listen to everyone. ideas come from everywhere",
    "living with a commitment to excellence shall take you far",
    "long life is in store for you",
    "love is a warm fire to keep the soul warm",
    "love is like sweet medicine, good to the last drop",
    "love lights up the world",
    "love truth, but pardon error.",
    "man is born to live and not prepared to live",
    "man’s mind, once stretched by a new idea, never regains it’s original dimensions",
    "many will travel to hear you speak",
    "meditation with an old enemy is advised",
    "miles are covered one step at a time",
    "nature, time and patience are the three great physicians",
    "never fear! the end of something marks the start of something new",
    "new ideas could be profitable",
    "new people will bring you new realizations, especially about big issues.",
    "no one can walk backwards into the future",
    "nothing is more difficult, and therefore more precious, than to be able to decide",
    "now is a good time to buy stock",
    "now is the time to go ahead and pursue that love interest",
    "now is the time to try something ne",
    "now is the time to try something new",
    "observe all men, but most of all yourself",
    "one can never fill another’s shoes, rather he must outgrow the old shoes",
    "one of the first things you should look for in a problem is its positive side",
    "others can help you now",
    "pennies from heaven find their way to your doorstep this year",
    "people are attracted by your delicate[sic] features",
    "people find it difficult to resist your persuasive manner",
    "perhaps you’ve been focusing too much on saving",
    "physical activity will dramatically improve your outlook today",
    "pick battles big enough to matter, small enough to win",
    "place special emphasis on old friendship",
    "please visit us at www.wontonfood.co",
    "po says: pandas like eating bamboo, but i prefer mine dipped in chocolate",
    "practice makes perfect",
    "protective measures will prevent costly disasters",
    "put your mind into planning today. look into the future",
    "remember the birthday but never the age",
    "remember to share good fortune as well as bad with your friends",
    "rest has a peaceful effect on your physical and emotional health",
    "resting well is as important as working hard",
    "romance moves you in a new direction",
    "savor your freedom – it is precious",
    "say hello to others. you will have a happier day",
    "self-knowledge is a life long process",
    "share your joys and sorrows with your family",
    "sift through your past to get a better idea of the present",
    "sloth makes all things difficult; industry all easy",
    "small confidences mark the onset of a friendship",
    "society prepares the crime; the criminal commits it",
    "someone you care about seeks reconciliation",
    "soon life will become more interesting",
    "stand tall. don’t look down upon yourself.",
    "staying close to home is going to be best for your morale toda",
    "stop searching forever, happiness is just next to you",
    "strong reasons make strong actions",
    "success is a journey, not a destination",
    "success is failure turned inside out",
    "success is going from failure to failure without loss of enthusiasm",
    "swimming is easy. stay floating is hard",
    "take care and sensitivity you show towards others will return to you",
    "take the high road",
    "technology is the art of arranging the world so we do not notice it",
    "the austerity you see around you covers the richness of life like a veil",
    "the best prediction of future is the past",
    "the change you started already have far-reaching effects. be ready",
    "the change you started already have far-reaching effects. be ready",
    "the first man gets the oyster, the second man gets the shell",
    "the greatest achievement in life is to stand up again after falling",
    "the harder you work, the luckier you get",
    "the night life is for you",
    "the one that recognizes the illusion does not act as if it is real",
    "the only people who never fail are those who never try",
    "the person who will not stand for something will fall for anything",
    "the philosophy of one century is the common sense of the next",
    "the saints are the sinners who keep on trying",
    "the secret to good friends is no secret to you.",
    "the small courtesies sweeten life, the greater ennoble it",
    "the smart thing to do is to begin trusting your intuitions",
    "the strong person understands how to withstand substantial loss",
    "the sure way to predict the future is to invent it",
    "the truly generous share, even with the undeserving",
    "the value lies not within any particular thing, but in the desire placed on that thing",
    "the weather is wonderful.",
    "there is no mistake so great as that of being always right",
    "there is no wisdom greater than kindness.",
    "there is not greater pleasure than seeing your lived",
    "there’s no such thing as an ordinary cat",
    "things don’t just happen; they happen just",
    "those who care will make the effort",
    "time and patience are called for many surprises await you!.",
    "time is precious, but truth is more precious than tim",
    "to know oneself, one should assert oneself",
    "to the world you may be one person, but to one person you may be the world",
    "today is the conserve yourself, as things just won’t budge",
    "today, your mouth might be moving but no one is listening",
    "tonight you will be blinded by passion",
    "use your eloquence where it will do the most good",
    "we first make our habits, and then our habits make us",
    "welcome change",
    "“welcome” is a powerful word",
    "well done is better than well said",
    "what’s hidden in an empty box",
    "what’s yours in mine, and what’s mine is mine",
    "when more become too much. it’s same as being not enough",
    "when your heart is pure, your mind is clear",
    "wish you happiness",
    "with age comes wisdom",
    "you always bring others happiness",
    "you are a person of another time",
    "you are a talented storyteller.",
    "you are admired by everyone for your talent and ability",
    "you are almost there",
    "you are busy, but you are happy",
    "you are generous to an extreme and always think of the other fellow",
    "you are going to have some new clothes.",
    "you are in good hands this evening",
    "you are interested in higher education, whether material or spiritual",
    "you are modest and courteous",
    "you are never selfish with your advice or your help",
    "you are next in line for promotion in your firm",
    "you are offered the dream of a lifetime. say yes",
    "you are open-minded and quick to make new friends.",
    "you are solid and dependable",
    "you are soon going to change your present line of work",
    "you are talented in many ways",
    "you are the master of every situation.",
    "you are very expressive and positive in words, act and feeling",
    "you are working hard",
    "you begin to appreciate how important it is to share your personal beliefs",
    "you can keep a secret",
    "you can see a lot just by looking",
    "you can’t steal second base and keep your foot on first",
    "you desire recognition and you will find it",
    "you have a deep appreciation of the arts and music",
    "you have a deep interest in all that is artistic",
    "you have a friendly heart and are well admired.",
    "you have a shrewd knack for spotting insincerity",
    "you have a yearning for perfection.",
    "you have an active mind and a keen imagination",
    "you have an ambitious nature and may make a name for yourself",
    "you have an unusual equipment for success, use it properly",
    "you have exceeded what was expected",
    "you have had a good start. work harder",
    "you have the power to write your own fortune",
    "you have yearning for perfection",
    "you know where you are going and how to get there",
    "you look pretty",
    "you love challenge",
    "you love chinese food",
    "you make people realize that there exist other beauties in the world",
    "you never hesitate to tackle the most difficult problems.",
    "you never know who you touch",
    "you only treasure what you lost",
    "you seek to shield those you love and like the role of provider.",
    "you should be able to make money and hold on to it",
    "you should be able to undertake and complete anything",
    "you should pay for this check. be generous",
    "you understand how to have fun with others and to enjoy your solitude",
    "you will always be surrounded by true friends",
    "you will always get what you want through your charm and personality",
    "you will always have good luck in your personal affairs",
    "you will be a great success both in the business world and society.",
    "you will be blessed with longevity",
    "you will be pleasantly surprised tonight",
    "you will be sharing great news with all the people you love",
    "you will be successful in your work",
    "you will be traveling and coming into a fortune",
    "you will be unusually successful in business",
    "you will become a great philanthropist in your later years",
    "you will become more and more wealthy",
    "you will enjoy good health",
    "you will enjoy good health; you will be surrounded by luxury",
    "you will find great contentment in the daily, routine activities",
    "you will have a fine capacity for the enjoyment of life",
    "you will have gold pieces by the bushel",
    "you will inherit a large sum of money",
    "you will make change for the better",
    "you will soon be surrounded by good friends and laughter",
    "you will take a chance in something in near future",
    "you will travel far and wide, both pleasure and business",
    "you will travel far and wide,both pleasure and business",
    "your abilities are unparalleled",
    "your ability is appreciated",
    "your ability to juggle many tasks will take you far",
    "your biggest virtue is your modesty",
    "your character can be described as natural and unrestrained",
    "your difficulties will strengthen you",
    "your dreams are never silly; depend on them to guide you",
    "your dreams are worth your best efforts to achieve them",
    "your energy returns and you get things done",
    "your family is young, gifted and attractive",
    "your first love has never forgotten you",
    "your goal will be reached very soon",
    "your happiness is before you, not behind you! cherish it",
    "your hard work will payoff today",
    "your heart will always make itself known through your words",
    "your home is the center of great love",
    "your ideals are well within your reach",
    "your infinite capacity for patience will be rewarded sooner or later",
    "your leadership qualities will be tested and proven",
    "your life will be happy and peaceful",
    "your life will get more and more exciting",
    "your love life will be happy and harmonious",
    "your love of music will be an important part of your life",
    "your loyalty is a virtue, but not when it’s wedded with blind stubbornness",
    "your mentality is alert, practical, and analytical",
    "your mind is creative, original and alert",
    "your mind is your greatest asset",
    "your moods signal a period of change",
    "your quick wits will get you out of a tough situation",
    "your reputation is your wealth",
    "your success will astonish everyone.",
    "your talents will be recognized and suitably rewarded",
    "your work interests can capture the highest status or prestige",
    "today it's up to you to create the peacefulness you long for",
    "a friend asks only for your time not your money",
    "if you refuse to accept anything but the best, you very often get it",
    "a smile is your passport into the hearts of others",
    "a good way to keep healthy is to eat more chinese food",
    "your high-minded principles spell success",
    "hard work pays off in the future, laziness pays off now",
    "change can hurt, but it leads a path to something better",
    "enjoy the good luck a companion brings you",
    "people are naturally attracted to you",
    "hidden in a valley beside an open stream- this will be the type of place where you will find your dream",
    "a chance meeting opens new doors to success and friendship",
    "you learn from your mistakes... you will learn a lot today",
    "if you have something good in your life, don't let it go",
    "what ever you're goal is in life, embrace it visualize it, and for it will be yours",
    "your shoes will make you happy today",
    "you cannot love life until you live the life you love",
    "be on the lookout for coming events; they cast their shadows beforehand",
    "land is always on the mind of a flying bird",
    "the man or woman you desire feels the same about you",
    "meeting adversity well is the source of your strength",
    "a dream you have will come true",
    "our deeds determine us, as much as we determine our deeds",
    "never give up. you're not a failure if you don't give up",
    "you will become great if you believe in yourself",
    "there is no greater pleasure than seeing your loved ones prosper",
    "you will marry your lover",
    "a very attractive person has a message for you",
    "you already know the answer to the questions lingering inside your head",
    "it is now, and in this world, that we must live",
    "you must try, or hate yourself for not trying",
    "you can make your own happiness",
    "the greatest risk is not taking one",
    "the love of your life is stepping into your planet this summer",
    "love can last a lifetime, if you want it to",
    "adversity is the parent of virtue",
    "serious trouble will bypass you",
    "a short stranger will soon enter your life with blessings to share",
    "now is the time to try something new",
    "wealth awaits you very soon",
    "if you feel you are right, stand firmly by your convictions",
    "if winter comes, can spring be far behind",
    "keep your eye out for someone special",
    "you are very talented in many ways",
    "a stranger, is a friend you have not spoken to yet",
    "a new voyage will fill your life with untold memories",
    "you will travel to many exotic places in your lifetime",
    "your ability for accomplishment will follow with success",
    "nothing astonishes men so much as common sense and plain dealing",
    "its amazing how much good you can do if you dont care who gets the credit",
    "everyone agrees. you are the best",
    "life consist not in holding good cards, but in playing those you hold well",
    "jealousy doesn't open doors, it closes them",
    "it's better to be alone sometimes",
    "when fear hurts you, conquer it and defeat it",
    "let the deeds speak",
    "you will be called in to fulfill a position of high honor and responsibility",
    "the man on the top of the mountain did not fall there",
    "you will conquer obstacles to achieve success",
    "joys are often the shadows, cast by sorrows",
    "fortune favors the brave",
    "an upward movement initiated in time can counteract fate",
    "a journey of a thousand miles begins with a single step",
    "sometimes you just need to lay on the floor",
    "never give up. always find a reason to keep trying",
    "if you have something worth fighting for, then fight for it",
    "stop wishing. start doing",
    "accept your past without regrets. handle your present with confidence. face your future without fear",
    "stay true to those who would do the same for you",
    "ask yourself if what you are doing today is getting you closer to where you want to be tomorrow",
    "happiness is an activity",
    "help is always needed but not always appreciated. stay true to your heart and help those in need weather they appreciate it or not",
    "hone your competitive instincts",
    "finish your work on hand don't be greedy",
    "for success today, look first to yourself",
    "your fortune is as sweet as a cookie",
    "integrity is the essence of everything successful",
    "if you're happy, you're successful",
    "you will always be surrounded by true friend",
    "believing that you are beautiful will make you appear beautiful to others around you",
    "happinees comes from a good life",
    "before trying to please others think of what makes you happy",
    "when hungry, order more chinese food",
    "your golden opportunity is coming shortly",
    "for hate is never conquered by hate. hate is conquered by love ",
    "you will make many changes before settling down happily",
    "a man is born to live and not prepare to live",
    "you cannot become rich except by enriching others",
    "don't pursue happiness - create it",
    "you will be successful in love",
    "all your fingers can't be of the same length",
    "wise sayings often fall on barren ground, but a kind word is never thrown away",
    "a lifetime of happiness is in store for you",
    "it is very possible that you will achieve greatness in your lifetime",
    "be tactful; overlook your own opportunity",
    "you are the controller of your destiny",
    "everything happens for a reson",
    "how can you have a beutiful ending without making beautiful mistakes",
    "you can open doors with your charm and patience",
    "welcome the change coming into your life",
    "there will be a happy romance for you shortly",
    "your fondest dream will come true within this year",
    "you have a deep interest in all that is artistic",
    "your emotional nature is strong and sensitive",
    "a letter of great importance may reach you any day now",
    "good health will be yours for a long time",
    "you will become better acquainted with a coworker",
    "to be old and wise, you must first be young and stupid",
    "failure is only the opportunity to begin again more intelligently",
    "integrity is doing the right thing, even if nobody is watching",
    "conquer your fears or they will conquer you",
    "you are a lover of words; one day you will write a book",
    "in this life it is not what we take up, but what we give up, that makes us rich",
    "fear can keep us up all night long, but faith makes one fine pillow",
    "seek out the significance of your problem at this time. try to understand",
    "never upset the driver of the car you're in; they're the master of your destiny until you get home",
    "he who slithers among the ground is not always a foe",
    "you learn from your mistakes, you will learn a lot today",
    "you only need look to your own reflection for inspiration. because you are beautiful",
    "you are not judged by your efforts you put in; you are judged on your performance",
    "rivers need springs",
    "good news from afar may bring you a welcome visitor",
    "when all else seems to fail, smile for today and just love someone",
    "patience is a virtue, unless its against a brick wall",
    "when you look down, all you see is dirt, so keep looking up",
    "if you are afraid to shake the dice, you will never throw a six",
    "even if the person who appears most wrong, is also quite often right",
    "a single conversation with a wise man is better than ten years of study",
    "happiness is often a rebound from hard work.",
    "the world may be your oyster, but that doesn't mean you'll get it's pearl",
    "your life will be filled with magical moments",
    "you're true love will show himself to you under the moonlight.",
    "do not follow where the path may lead. go where there is no path...and leave a trai",
    "do not fear what you don't kno",
    "the object of your desire comes closer",
    "you have a flair for adding a fanciful dimension to any story",
    "if you wish to know the mind of a man, listen to his word",
    "the most useless energy is trying to change what and who god so carefully created",
    "do not be covered in sadness or be fooled in happiness they both must exis",
    "you will have unexpected great good luck",
    "you will have a pleasant surpris",
    "all progress occurs because people dare to be different",
    "your ability for accomplishment will be followed by success",
    "the world is always ready to receive talent with open arms",
    "things may come to those who wait, but only the things left by those who hustle",
    "we can't help everyone. but everyone can help someone",
    "every day is a new day. but tomorrow is never promised",
    "express yourself: don't hold back",
    "it is not necessary to show others you have change; the change will be obvious",
    "you have a deep appreciation of the arts and music",
    "if your desires are not extravagant, they will be rewarded",
    "you try hard, never to fail. you don't, never to win",
    "never give up on someone that you don't go a day without thinking about",
    "it never pays to kick a skunk",
    "in case of fire, keep calm, pay bill and run",
    "next full moon brings an enchanting evening",
    "not all closed eye is sleeping nor open eye is seeing",
    "impossible is a word only to be found in the dictionary of fools",
    "you will soon witness a miracle",
    "the time is alway right to do what is right",
    "love is as necessary to human beings as food and shelter",
    "you will make heads turn",
    "you are extremely loved. don't worry :",
    "if you are never patient, you will never get anything done. if you believe you can do it, you will be rewarded with success",
    "you will soon embark on a business venture",
    "you believe in the goodness of man kind",
    "you will have a long and wealthy life",
    "you will take a pleasant journey to a place far away",
    "you are a person of culture",
    "keep it simple. the more you say, the less people remember",
    "life is like a dogsled team. if you ain't the lead dog, the scenery never changes",
    "prosperity makes friends and adversity tries them",
    "nothing seems impossible to you",
    "patience is bitter, but its fruit is sweet",
    "the only certainty is that nothing is certain",
    "success is the sum of my unique visions realized by the sweat of perseverance",
    "when you expect your opponent to yield, you also should avoid hurting him",
    "human evolution: 'wider freeway' but narrower viewpoints",
    "intelligence is the door to freedom and alert attention is the mother of intelligence",
    "back away from individuals who are impulsive",
    "enjoyed the meal? buy one to go too",
    "you believe in the goodness of mankind",
    "a big fortune will descend upon you this year.",
    "now these three remain, faith, hope, and love. the greatest of these is love",
    "for success today look first to yourself",
    "determination is the wake-up call to the human will",
    "there are no limitations to the mind except those we aknowledge",
    "a merry heart does good like a medicine",
    "whenever possible, keep it simple",
    "your dearest wish will come true.",
    "poverty is no disgrace",
    "if you don’t do it excellently, don’t do it at all",
    "you have an unusual equipment for success, use it properly",
    "emotion is energy in motion",
    "you will soon be honored by someone you respect",
    "punctuality is the politeness of kings and the duty of gentle people everywhere",
    "your happiness is intertwined with your outlook on life",
    "elegant surroundings will soon be yours",
    "if you feel you are right, stand firmly by your convictions",
    "your smile brings happiness to everyone you meet",
    "instead of worrying and agonizing, move ahead constructively",
    "do you believe? endurance and persistence will be rewarded.",
    "a new business venture is on the horizon",
    "never underestimate the power of the human touch",
    "hold on to the past but eventually, let the times go and keep the memories into the present",
    "truth is an unpopular subject. because it is unquestionably correct",
    "the most important thing in communication is to hear what isn’t being said",
    "you are broad minded and socially active",
    "your dearest dream is coming true. god looks after you especially.",
    "you will recieve some high prize or award",
    "your present question marks are going to succeed",
    "you have a fine capacity for the enjoyment of life",
    "you will live long and enjoy life",
    "an admirer is concealing his/her affection for you",
    "a wish is what makes life happen when you dream of rose petals",
    "love can turn cottage into a golden palace.",
    "lend your money and lose your freind",
    "you will kiss your crush ohhh lalah",
    "you will be rewarded for being a good listener in the next week",
    "if you never give up on love, it will never give up on you.",
    "unleash your life force.",
    "your wish will come true",
    "there is a prospect of a thrilling time ahead for you",
    "no distance is too far, if two hearts are tied together.",
    "land is always in the mind of the flying birds",
    "try? no! do or do not, there is no try",
    "do not worry, you will have great peace",
    "it's about time you asked that special someone on a date",
    "you create your own stage ... the audience is waiting",
    "it is never too late. just as it is never too early",
    "discover the power within yourself.",
    "good things take time.",
    "stop thinking about the road not taken and pave over the one you did",
    "put your unhappiness aside. life is beautiful, be happy",
    "you can still love what you can not have in life",
    "make a wise choice everyday",
    "circumstance does not make the man; it reveals him to himself",
    "the man who waits till tomorrow, misses the opportunities of today",
    "life does not get better by chance. it gets better by change",
    "if you never expect anything you can never be disappointed",
    "people in your surroundings will be more cooperative than usual",
    "true wisdom is found in happiness",
    "ones always regrets what could have done. remember for next time",
    "follow your bliss and the universe will open doors where there were once only walls",
    "find a peaceful place where you can make plans for the future.",
    "all the water in the world can't sink a ship unless it gets inside",
    "the earth is a school learn in it",
    "in music, one must think with his heart and feel with his brain",
    "if you speak honestly, everyone will listen",
    "ganerosity will repay itself sooner than you imagine",
    "good things take tim",
    "do what is right, not what you should.",
    "to effect the quality of the day is no small achievement",
    "simplicity and clearity should be the theme in your dress",
    "virtuous find joy while wrongdoers find grieve in their actions",
    "not all closed eye is sleeping, nor open eye is seeing.",
    "bread today is better than cake tomorrow",
    "in evrything there is a piece of truth.but a piece",
    "a feeling is an idea with roots",
    "man is born to live and not prepare to live",
    "it's all right to have butterflies in your stomach. just get them to fly in formation.",
    "if you don t give something, you will not get anythin",
    "the harder you try to not be like your parents, the more likely you will become the",
    "someday everything will all make perfect sens",
    "you will think for yourself when you stop letting others think for yo",
    "everything will be ok. don't obsess. time will prove you right, you must stay where you are",
    "let's finish this up now, someone is waiting for you on tha",
    "the finest men like the finest steels have been tempered in the hottest furnace",
    "a dream you have will come true",
    "the worst of friends may become the best of enemies, but you will always find yourself hanging on.",
    "i think, you ate your fortune while you were eating your cooki",
    "if u love someone keep fighting for them",
    "do what you want, when you want, and you will be rewarde",
    "let your fantasies unwind...",
    "the cooler you think you are the dumber you loo",
    "expect great things and great things will come",
    "the wheel of good fortune is finally turning in your direction",
    "don't lead if you won't lead",
    "you will always be successful in your professional career",
    "share your hapiness with others today",
    "it's up to you to clearify",
    "your future will be happy and productive",
    "seize every second of your life and savor it",
    "those who walk in other's tracks leave no footprints",
    "failure is the mother of all success.",
    "difficulty at the beginning useually means ease at the end",
    "do not seek so much to find the answer as much as to understand the question better.",
    "your way of doing what other people do their way is what makes you special",
    "a beautiful, smart, and loving person will be coming into your life.",
    "friendship is an ocean that you cannot see bottom",
    "your life does not get better by chance, it gets better by change.",
    "our duty,as men and women,is to proceed as if limits to our ability did not exist",
    "a pleasant expeience is ahead:don't pass it by.",
    "our perception and attitude toward any situation will determine the outcom",
    "they say you are stubborn; you call it persistence",
    "two small jumps are sometimes better than one big leap",
    "a new wardrobe brings great joy and change to your life",
    "the cure for grief is motion",
    "it's a good thing that life is not as serious as it seems to the waite",
    "i hear and i forget. i see and i remember. i do and i understand",
    "i have a dream....time to go to bed",
    "ideas you believe are absurd ultimately lead to success!",
    "a human being is a deciding being",
    "today is an ideal time to water your parsonal garden",
    "some men dream of fortunes, others dream of cookies",
    "things are never quite the way they seem",
    "the project on your mind will soon gain momentu",
    "your failures will lead you to your success",
    "in order to get the rainbow, you must endure the rain.",
    "beauty is simply beauty. originality is magical",
    "your dream will come true when you least expect it",
    "let not your hand be stretched out to receive and shut when you should repay",
    "don't worry, half the people you know are below average.",
    "vision is the art of seeing what is invisible to others",
    "you don't need talent to gain experience",
    "a focused mind is one of the most powerful forces in the universe",
    "today you shed your last tear. tomorrow fortune knocks at your door",
    "be patient! the great wall didn't got build in one day.",
    "think you can. think you can't. either way, you'll be right",
    "wisdom is on her way to you.",
    "digital circuits are made from analog parts.",
    "if you eat a box of fortune cookies, anything is possible",
    "the best is yet to come.",
    "i'm with you.",
    "be direct,usually one can accomplish more that way.",
    "a single kind work will keep one warm for years.",
    "ask a friend to join you on your next voyage",
    "in god we trust",
    "love is free. lust will cost you everything you have.",
    "stop searching forever, happiness is just next to you.",
    "you don't need the answers to all of life's questions. just ask your father what to do",
    "jealousy is a useless emotion.",
    "you are not a ghost.",
    "there is someone rather annoying in your life that you need to listen to",
    "you will plant the smallest seed and it will become the greatest and most mighty tree in the world",
    "the dream you've been dreaming all your life isn't worth it. find a new dream, and once you're sure you've found it, fight for it",
    "see if you can learn anything from the children",
    "it's never too late for good things to happen",
    "a clear conscience is usually the sign of a bad memory",
    "aim high, time flies",
    "one is not sleeping, does not mean they are awake",
    "a great pleasure in life is doing what others say you can't",
    "isn't there something else you should be working on right now?",
    "your father still loves and is in always with you. remember that",
    "before you can be reborn you must die",
    "it better to be the hammer than the nail.",
    "you are admired by everyone for your talent and ability.",
    "save the whales. collect the whole set.",
    "you will soon discover a major truth about the one you love most.",
    "your life will prosper only if you acknowledge your faults and work to reduce them",
    "pray to god, but row towards shore",
    "you will soon witness a miracle.",
    "the early bird gets the worm, but the second mouse gets the cheese",
    "help, i'm being held prisoner in a chinese cookie factory.",
    "alas! the onion you are eating is someone else’s water lily",
    "you are a persoon with a good sense of justice, now it's time to act like it",
    "you create enthusiasm around you",
    "there are big changes ahead for you. they will be good ones",
    "you will have many happy days soon",
    "out of confusion comes new patterns",
    "if you love someone enough and they break your heart, you can't stop yourself from still loving them again even after all that pain",
    "look right...now look left...now look forward",
    "live like you are on the bottom, even if you are on the top.",
    "you will soon emerge victorious from the maze you've been traveling in.",
    "do not judge a book by it's color.",
    "everything will come your way.",
    "there is a time to be practical now",
    "bend the rod while it is still hot",
    "darkness is only succesful when there is no light. don't forget about light!",
    "acting is not lying. it is findind someone hiding inside you and letting that person run free",
    "you will be forced to face fear, but if you do not run, fear will be afraid of you",
    "you are thinking about doing something. don't do it, it won't help anything",
    "your worst enemy has a crush on you",
    "love conquers all.",
    "the phrase is follow your dreams. not dream period",
    "stop nagging to your partner and take it day by day.",
    "do not think that me or my brothers have supreme control over what will happen to you",
    "bad luck and misfortune will follow you all your days.",
    "remember the fate of the early worm",
    "begin your life anew with strength, grace and wonder",
    "be a good friend and a fair enemy.",
    "what goes around comes around.",
    "bad luck and misfortune will infest your pathetic soul for all eternity.",
    "the best prophet of the future is the pas",
    "movies have pause buttons, friends do no",
    "use the force",
    "trust your intuition",
    "encourage your peers.",
    "let your imagination wander",
    "your pain is the breaking of the shell that encloses your understanding",
    "patience is key, a wait short or long will have its reward",
    "tell them before it's too late..",
    "a bird in the hand is worth three in the bush!",
    "be assertive when decisive action is needed",
    "to determine whether someone is beautiful is not by looking at his/her appearance, but his/her heart.",
    "hope brings about a better futur",
    "while you have this day, fill it with life. while you're in this moment, give it your own special meaning and purpose and joy",
    "even though it will often be difficult and complicated, you know you have what it takes to get it done",
    "you will prosper in the field of wacky inventions",
    "your tongue is your ambassador",
    "the cure for grief is movement.",
    "love is at your hands be glad and hold on to it.",
    "you are often asked if it is in yet",
    "life to you is a bold and dashing responsibility.",
    "patience is a key to joy.",
    "a bargain is something you don't need at a price you can't resist",
    "today is going to be a disasterous day, be prepared",
    "stay to your inner-self, you will benefit in many ways.",
    "rarely do great beauty and great virtue dwell together as they do in you",
    "you are talented in many ways",
    "you are the master of every situation",
    "your problem just got bigger. think, what have you done.",
    "if your cookie still in one piece, buy lotto",
    "go with the flow will make your transition ever so much easier.",
    "tomorrow morning,take a left turn as soon as you leave home",
    "a metaphor could save your life.",
    "don't wait for your ship to come in, swim out to it",
    "there are lessons to be learned by listening to others",
    "if you want the rainbow, you have to tolerate the rain.",
    "volition, strength, languages, freedom and power rests in you",
    "it takes more than a good memory to have good memories.",
    "you are what you are; understand yourself before you reac",
    "word to the wise: don't play leapfrog with a unicorn........",
    "forgive your enemies, but never forget them",
    "everything will now come your way",
    "don't worry about the stock market. invest in family",
    "your fortune is as sweet as a cookie.",
    "it is much easier to look for the bad, than it is to find the goo",
    "if a person who has caused you pain and suffering has brought you, reconsider that person's value in your life",
    "you are worth loving, you are also worth the effort it takes to love you",
    "never trouble trouble till trouble troubles you.",
    "get off to a new start - come out of your shell.",
    "life is a dancefloor,you are the dj",
    "cooperate with those who have both know how and integrith",
    "minor aches today are likely to pay off handsomely tomorrow",
    "you are about to become $8.95 poorer.",
    "your mouth may be moving, but nobody is listening",
    "focus in on the color yellow tomorrow for good luck!",
    "the problem with resisting temptation is that it may never come again",
    "all your sorrows will vanish.",
    "about time i got out of that cookie",
    "love will lead the way",
    "the ads revenge is massive succes",
    "it is best to act with confidence, no matter how little right you have to it",
    "soon, a visitor shall delight you.",
    "what breaks in a moment may take years to mend",
    "someone stole your fortune and replaced it with this one. your luck sucks. have a good day",
    "take control of your life rather than letting things happen just like that!",
    "you will be rewarded for your patience and understanding.",
    "you will achieve all your desires and pleasures.",
    "never miss a chance to keep your mouth shut.",
    "nothing shows a man's character more than what he laughs at",
    "never regret anything that made you smile.",
    "love takes pratice.",
    "don't take yourself so seriously, no one else does.",
    "you've got what it takes, but it will take everything you've got",
    "at this very moment you can change the rest of your life.",
    "become who you are.",
    "all comes at the proper time to him who knows how to wait",
    "the energy is within you. money is coming",
    "the quotes that you do not understand, are not meant for you",
    "you have an important new business development shaping up",
    "if love someone a lot tell it before it's too late",
    "birds are entangled by their feet and men by their tongues.",
    "benefit by doing things that others give up on",
    "rest has a peaceful effect on your physical and emotional health",
    "one of the best ways to persuade others is with your ears--by listening to them.",
    "plan your work and work your plan",
    "over self-confidence is equal to being blind.",
    "those who bring sunshine to the lives of others cannot keep it from themselves.",
    "love or money, or neither?",
    "before the beginning of great brilliance, there must be chaos",
    "old friends make best friends.",
    "stop searching forever. happiness is just next to you.",
    "accept something that you cannot change, and you will feel better",
    "kiss is not a kiss without the heart.",
    "enhance your karma by engaging in various charitable activities.",
    "you will have good luck and overcome many hardships.",
    "you never hesitate to tackle the most difficult problems",
    "hope is like food. you will starve without it",
    "when fire and water go to war water always wins.",
    "an angry man opens his mouth and shuts up his eyes",
    "make the system work for you, not the other way around.",
    "you will be hungry soon, order takeout now",
    "be prepared for extra energy",
    "an unexpected relationship will become permanent.",
    "the love of your life is sitting across from you.",
    "better be the head of a chicken than the tail of an ox",
    "to forgive others one more time is to create one more blessing for yourself",
    "enjoy yourself while you can.",
    "the ultimate test of a relationship is to disagree but to hold hands",
    "excellence is the difference between what i do and what i am capable of",
    "do not let what you do not have prevent you from using what you do have",
    "what ends on hope does not end at all",
    "people enjoy having you around. appreciate this",
    "you are admired for your adventuous ways",
    "it's never crowded along the 'extra mile",
    "you are blessed, today is the day to bless others",
    "the greatest war sometimes isn't on the battlefield but against oneself",
    "people in your background will be more co-operative than usual",
    "a good way to stay healthy is to eat more chinese food.",
    "anyone who dares to be, can never be weak",
    "affirm it, visualize it, believe it, and it`will actualize itself",
    "the measure of time to your next goal is the measure of your discipline",
    "help, i'm prisoner in a chinese bakery!!!",
    "take a minute and let it ride, then take a minute to let it breeze.",
    "we are here to love each other, serve each other and uplift each other.",
    "if everybody is a worm you should be a glow wor",
    "to affirm is to make firm.",
    "remember this: duct tape can fix anything, so don't worry about messing things up",
    "you broke my cookie!",
    "failure is not defeat until you stop trying.",
    "the days that make us happy make us wise",
    "men do not fail... they give up trying",
    "time may fly by. but memories don't",
    "you will win success in whatever you adopt",
    "you will outdistance all your competitors.",
    "you have a great capability to break cookies - use it wisely!",
    "at times it is better to know when exit than enter",
    "money will come to you when you are doing the right thing.",
    "when you get something for nothing, you just haven't been billed for it yet",
    "you will discover your hidden talents.",
    "you'll advance for with your abilities",
    "when you can't naturally feel upbeat it can sometimes help you to act as if you did",
    "you will overcome difficult times.",
    "your problem just became your stepping stone. catch the moment",
    "i am a fortune. you just broke my little house. where will i live now?",
    "the majority of the word 'can't' is can.",
    "the secret of getting ahead is getting started.",
    "be most affectionate today.",
    "change your thoughts and you change the world",
    "sing and rejoice, fortune is smiling on you.",
    "all the preparation you've done will finally be paying off!",
    "a truly great person never puts away the simplicity of a child",
    "customer service is like taking a bath you have to keep doing it",
    "the expanse of your intelligence is a void no universe could ever fill",
    "those grapes you cannot taste are always sour",
    "an unexpected aquaintance will resurface",
    "if you want the rainbow, then you have to tolerate the rain",
    "you don't get harmony when everyone sings the same note.",
    "the race is not always to the swift, but to those who keep on running",
    "the early bird gets the worm, but the second mouse gets the cheese.",
    "the best things in life aren't things",
    "don't bother looking for fault. the reward for finding it is low",
    "everything has beauty but not everyone sees it",
    "nothing is as good or bad as it appears",
    "never cut what you can untie",
    "meet your opponent half way. you need the exercise",
    "laughter is the shortest distance between two people",
    "we cannot change the direction of the wind, but we can adjust our sails",
    "we could learn a lot from crayons: some of are sharp, some are pretty, some have weird names, and all are different colors. but they all have to learn to live in the same box.",
    "use your instincts now.",
    "if you take a single step to your journey, you'll succeed; it's not best to fail",
    "in the eyes of lovers, everything is beautiful.",
    "warning, do not eat your fortune.",
    "demonstrate refinement in everything you do.",
    "impossible standards just make life difficult",
    "a different world cannot be build by indifferent people",
    "q. what is h2o? a. caring, 2 parts hug and 1 part open-mind.",
    "all troubles you have can pass away very quickly",
    "integrity is the essense of everything successful.",
    "for true love? send real roses preserved in 24kt gold!",
    "sometimes the object of the journey is not the end, but the journey itself.",
    "fear is just excitement in need of an attitude adjustment.",
    "the food here taste so good, even a cave man likes it.",
    "perhaps you've been focusing too much on spending",
    "happiness isn't something you remember, it's something you experience.",
    "oops... wrong cookie.",
    "the dream is within you",
    "love is on its way.",
    "be direct, usually one can accomplish more that way",
    "use your talents. that's what they are intended for.",
    "the troubles you have now will pass away quickly.",
    "see the light at the end of the tunnel",
    "your dream will come true when you least expect it.",
    "don't 'face' reality, let it be the place from which you leap.",
    "fortune smiles upon you today.",
    "believing is doing",
    "your dynamic eyes have attracted a secret admirer.",
    "you know where you are going and how to get there.",
    "go confidently in the direction of your dreams.",
    "your ability to pick a winner will bring you success.",
    "humor usually works at the moment of awkwardness.",
    "a good time to finish up old tasks.",
    "stop procrastinating - starting tomorrow",
    "enthusiastic leadership gets you a promotion when you least expect it",
    "you love chinese food.",
    "you are far more influential than you think.",
    "adjust finances, make budgets, to improve your standing",
    "happiness is not the absence of conflict, but the ability to cope with it",
    "an understanding heart warms all that are graced with it's presense.",
    "your co-workers take pleasure in your great sense of creativity",
    "you are one of the people who 'goes places' in life",
    "others enjoy your company.",
    "when in doubt, let your instincts guide you",
    "a cheerful message is on its way to you.",
    "a pleasant surprise is in store for you tonight.",
    "you cant go down the right path with out first discovering the path to go dow",
    "to courageously shoulder the responsibility of one's mistake is character.",
    "the joyful energy of the day will have a positive affect on you",
    "you have a strong desire for a home and your family interests come first.",
    "dogs have owners, cats have staff.",
    "be patient: in time, even an egg will walk.",
    "you are not a person who can be ignored.",
    "you always know the right times to be assertive or to simply wait",
    "reading to the mind is what exercise is to the body.",
    "eat something you never tried before",
    "your life becomes more and more of an adventure!",
    "you need to live authentically, and you can't ignore that",
    "make all you can, save all you can, give all you can.",
    "a well-aimed spear is worth three",
    "to build a better world, start in your community",
    "when you can't naturally feel upbeat, it can sometimes help to act a if you did",
    "may you have great luck.",
    "a kind word will keep someone warm for years",
    "nothing in the world is accomplished without passion",
    "human invented language to satisfy the need to complain",
    "accept what comes to you each day",
    "a small lucky package is on its way to you soon.",
    "in human endeavor, chance favors the prepared mind",
    "do not upset the penguin today.",
    "don't cry.",
    "the best way to give credit is to give it away.",
    "anything you do, do it well. the last thing you want is to be sorry for what you didn't do",
    "it takes more then good memory to have good memories.",
    "grant yourself a wish this year only you can do it.",
    "love thy neighbour, just don't get caught",
    "you will be selected for a promotion because of your accomplishments.",
    "there are many new opportunities that are being presented to you.",
    "you will inherit a large sum of money.",
    "you will recieve a gift from someone that cares about you",
    "you are not illiterate.",
    "love because it is the only true adventure",
    "you are contemplating some action which will bring credit upon yo",
    "keep true to the dreams of your youth",
    "treasure what you have.",
    "the greatest precept is continual awareness.",
    "a new friend helps you break out of an old routine",
    "i have a dream.... time to go to bed.",
    "your skill will accomplish what the force of many cannot",
    "you will soon be surrounded by good friends and laughter.",
    "the best is yet to come",
    "it is better to be the hammer then the anvil",
    "he who climbs a ladder must begin at the first step",
    "action speaks nothing, without the motive.",
    "give yourself some peace and quiet for at least a few hours.",
    "live each day well and wisely",
    "old dreams never die they just get filed away",
    "you can fix it with a little extra energy and a positive attitude",
    "life is a ver",
    "a man without aim is like a clock without hands, as useless if it turns as if it stands.",
    "many folks are about as happy as they make up their minds to be",
    "it's kind of fun to do the impossible",
    "wow! a secret message from you teeth!",
    "you should be able to make money and hold on to it.",
    "the human spirit is stronger than anything that can happen to it.",
    "your succeess will astonish everyone",
    "it is better to have a hen tomorrow than an egg today",
    "judge each day not by the harvest you reap but by the seeds you plant.",
    "you like chinese food.",
    "your hard work will get payoff today.",
    "today is the tomorrow we worried about yesterda",
    "there are no shortcuts to any place worth goin",
    "no matter what your past has been, you have a spotless future",
    "your secret desire to completely change your life will manifest.",
    "soon you will be sitting on top of the world.",
    "you are never selfish with your advice or your help",
    "a thrilling time is in store for you.",
    "it's tough to be fascinating.",
    "soon life will become more interestin",
    "luck sometimes visits a fool, but it never sits down with him",
    "keep your plans secret for now.",
    "aren't you glad you just had a great meal",
    "traveling this year will bring your life into greater perspective.",
    "only talent people get help from others",
    "constant grinding can turn an iron nod into a needle",
    "you will be successful in your wor",
    "you will spend old age in confort and material wealt",
    "when you're about to turn your heart into a stone remember: you do not walk alone",
    "i am a bad luck person since i was born",
    "you are vigorous in words and action.",
    "the one who snores will always fall asleep first.",
    "an alien of some sort will be appearing to you shortly!",
    "rest is a good thing, but boredom is its brother",
    "do not be overly judgemental of your loved one's intentions or actions",
    "think of how you can assist on a problem, not who to blame",
    "the life of every woman or man - the heart of it - is pure and holy joy",
    "take it easy",
    "trust your intuition. the universe is guiding your life.",
    "use your head, but live in your heart.",
    "don't find fault, find a remed",
    "it may be those who do most, dream most",
    "your passions sweep you away",
    "listen to yourself more often",
    "think of mother's exhortations more",
    "the gambler is like the fisherman both have beginners luck",
    "you are given the chance to take part in an exciting adventure.",
    "the simplest answer is to act.",
    "you will always be surrounded by true friends.",
    "keep your feet on the ground even though friends flatter you.",
    "you are the man of righteousness and integrity",
    "he who seeks will find.",
    "the smart thing to do is to begin trusting your intuitions",
    "your many hidden talents will become obvious to those around you",
    "pick a path with heart",
    "the human spirit is stronger then anything that can happen to it",
    "it takes more than good memory to have good memories",
    "face facts with dignity.",
    "be calm when confronting an emergency crisis",
    "do you believe? endurance and persistence will be rewarded.",
    "a new wardrobe brings great joy and change in your life.",
    "everyone agrees you are the best.",
    "a new outlook brightens your image and brings new friends.",
    "everything will now come your way",
    "you will be called to fill a position of high honor and responsibility",
    "the eyes believe themselves; the ears believe other people",
    "good beginning is half done.",
    "some pursue happiness; you create it.",
    "it's the worst of times, you need to summon your optimism",
    "you are cautious in showing your true self to others.",
    "your ability to accomplish tasks will follow with success.",
    "we all have extraordinary coded within us, waiting to be released.",
    "you will have a bright future.",
    "compassion is a way of being",
    "you will always have good luck in your personal affairs.",
    "the pleasure of what we enjoy is lost by wanting mor",
    "did you remember to order your take out also",
    "perhaps you've been focusing too much on that one thing..",
    "right now there's an energy pushing you in a new direction.",
    "everybody feels lucky for having you as a friend",
    "when the moment comes, take the top one.",
    "sometimes travel to new places leads to great transformation",
    "there is always a way - if you are committed",
    "life is too short to waste time hating anyone",
    "all the world may not love a lover but they will be watching him.",
    "don't just spend time, invest it",
    "life always gets harder near the summit",
    "take the chance while you still have the choice.",
    "it is much easier to be cirtical than to be correct.",
    "enjoy life! it is better to be happy than wise.",
    "to make the cart go, you must grease the wheels",
    "you are contemplating some action which will bring credit upon you",
    "before you wonder 'am i doing things right', ask 'am i doing the right things?'",
    "you may be disappointed if you fail, but you are doomed if you don't try.",
    "you will always get what you want through your charm and personality",
    "the big issues are work, career, or status right now",
    "your emotional currents are flowing powerfully now",
    "any decision you have to make tomorrow is a good decsion.",
    "consume less. share more. enjoy life",
    "the secret of staying young is good health and lying about your age",
    "spring has sprung. life is blooming",
    "go ask your mom.",
    "the possibility of a career change is near",
    "the important thing is to never stop questioning",
    "compassion will cure more then condemnation",
    "excuses are easy to manufacture, and hard to sell.",
    "put your mind into planning today. look into the future",
    "listen to life, and you will hear the voice of life crying, be!",
    "broke is only temporaryl poor is a state of mind",
    "teamwork: the fuel that allows common people attain uncommon results",
    "hard words break no bones, fine words butter no parsnips",
    "we cannot direct the wind but we can adjust the sails.",
    "you are offered the dream of a lifetime. say yes!",
    "working out the kinks today will make for a better tomorrow",
    "you have a curious smile and a mysterious nature.",
    "questions provide the key to unlocking our unlimited potential.",
    "you will enjoy razon-sharp spiritual vision today",
    "the wise are aware of their treasure, while fools follow their vanit",
    "well-arranged time is the surest sign of a well-arranged mind",
    "never bring unhappy feelings into your home.",
    "this is really a lovely day. congratulations",
    "bad luck and ill misfortune will infest your pathetic soul for all eternity.",
    "a golden egg of opportunity falls into your lap this month.",
    "you are very grateful for the small pleasures of life.",
    "today you should be a passenger. stay close to a driver for a day",
    "for hate is never conquered by hate. hate is conquered by love",
    "service is the rent we pay for the privilege of living on this planet",
    "good clothes open many doors. go shopping.",
    "the leader seeks to communicate his vision to his followers.",
    "great works are performed not by strength, but by perseverance.",
    "people who are late are often happier than those who have to wait for them",
    "present your best ideas today to an eager and welcoming audience",
    "friends long absent are coming back to you.",
    "the time is right to make new friends",
    "life to you is a dashing and bold adventur",
    "you may be hungry soon: order a takeout now.",
    "do not hesitate to look for help, an extra hand should always be welcomed",
    "how can you have a beautiful ending without making beautiful mistakes?",
    "humor is an affirmation of dignit",
    "he who climbs a ladder must begin at the first ste",
    "what's vice today may be virtue tomorow",
    "you have an unusually magnetic personality",
    "you will travel to many places.",
    "accept yourself",
    "be a generous friend and a fair enem",
    "never quit!",
    "old friends, old wines and old gold are best",
    "if your desires are not extravagant, they will be granted",
    "every friend joys in your success",
    "you should be able to undertake and complete anythin",
    "you will enjoy good health, you will be surrounded by luxur",
    "you are a person of strong sense of dut",
    "dream lofty dreams, and as you dream, so shall you become",
    "you have a quiet and unobtrusive nature",
    "great thoughts come from the heart",
    "you love peac",
    "judge not according to the appearance",
    "one who admires you greatly is hidden before your eyes.",
    "traveling more often is important for your health and happiness",
    "you will be sharing great news with all people you love",
    "you have a reputation for being straightforward and honest",
    "you are always welcome in any gathering",
    "you will be traveling and coming into a fortune.",
    "open up your heart - it can always be closed again",
    "being happy is not always being perfect",
    "next time you have the opportunity, go on a rollercoaster",
    "try everything once, even the things you don't think you will like",
    "life is too short to hold grudges",
    "dream your dream and your dream will dream of you.",
    "being alone and being lonely are two different things.",
    "tomorrow, take a moment to do something just for yourself",
    "someone close to you is waiting for you to call",
    "a virtual fortune cookie will not satisfy your hunger like that of a home made one.",
    "smile. tomorrow is another day",
    "you can never been certain of success, but you can be certain of failure if you never try.",
    "it takes ten times as many muscles to frown as it does to smile",
    "shoot for the moon! if you miss you will still be amongst the stars.",
    "keep your eyes open. you never know what you might see.",
    "tell them what you really think. otherwise, nothing will change.",
    "let your heart make your decisions - it does not get as confused as your head.",
    "working hard will make you live a happy life",
    "a pleasant surprise is waiting for you."
  ]
 

 exports.getFortune = () => fortunes[Math.floor(Math.random() * fortunes.length)];