let haikus = [
		"I've been training for\nthe last few days and it's not\neven good anymore",
		"No matter what i\njust know you're gonna get it\ncause you deserve it",
		"You just feel like\nyou're in a fucking mess and\ndon't know what to do",
		"I wanna get high\nbut I don't wanna get drunk\nbut I can't go see it",
		"I'm sorry but this\nis not happening to you\nYou deserve better",
		"You ever see a\nkid in a photo and think\nyou're crazy okay",
		"i'm glad i know what\nit's like to see someone that\nsays something to you",
		"they're just waiting\nfor me to do something\nI don't like to do",
		"i really wanna\ngo back to where i was in\nschool and fall asleep",
		"I'm actually\nso excited to see what\nI'm missing today",
		"I need someone to\ntalk to about stuff I want\nto talk about shit",
		"I'm so ready to\nfind a new channel to watch\nanime with my friends",
		"Whoever gave you\nmoney can never be king\nof the world No thanks",
		"I guess I'm gonna\nmake a video about\nhow I lost my ear",
		"Eating cereal\nis one of the most boring\nthings ever really",
		"Every time I\nget a cold I get really\na bit tired out",
		"I honestly just\ndon't want to do anything\nfor people anymore",
		"I'm really trying\nto just be cute and be a\nbear forever lol",
		"I know the Eagles\nwon the Super Bowl but I\nain't care about that",
		"I'm trying to be\na good vibe person but I\nhave bad hair that's it",
		"I can't even\nimagine how thankful I\nam for all the love",
		"Should get some new headphones\nto listen to on my phone\ntoday I need them",
		"I don't ever get\nmad because I'm mad at you\nbut I'm mad at myself",
		"You know you gotta\nkeep it real when you're just like\nmyself on your phone",
		"I'm always on the\nlookout for the perfect\ntime to go to sleep",
		"If you're willing to\ndownload the free app that will\nmake a huge difference",
		"I have so many\namazing friends that I can\nsee so many things",
		"Missed the whole month\nof December just to\naccommodate",
		"I'm not going to\ngo to Paris tomorrow\nI'm going to London",
		"I'm just gonna have\nto go through the whole thing and\njust let it go by",
		"My mom is so nice\nto me and just keep on giving\nme the best of luck",
		"If you haven't heard\nanything about me since I\nmade a new video",
		"Hate is this bit of\nlogic that could only be\nused to guide you through it",
		"Wish I was that guy\nthat had to take a short trip to\nFlorida for winter",
		"Honestly I should\nbe doing this but I just\ndon't want to do it",
		"Should be refreshing\nto go ahead and do this\nI'm not bothered by it",
		"I remember the\ntimes I used Twitter to talk\nto people in real time",
		"What a great feeling\nI've got to be thankful for\nmy friends and family",
		"I'm feeling really\nsick Are you guys going to\ngo back to sleep now",
		"I really need to\nget a new phone now I don't\nhave one anymore",
		"I've been saying this\nall day and it's still not true\nI just need a new phone",
		"So excited to\nrelease the new album this\nyear It's so dope Thank you",
		"Should've lost my phone\non the way home but it's so\nuseless i guess",
		"the skills gap is\nkilling me don't let people\nclassify my brain Lol",
		"I hate being sick\nbut I like being around\nmy loved ones so much",
		"I really want to\nleave work and go to a bar\nwith a friend tonight",
		"I'm the reason why\nwhen things don't work out I want\nto keep going forward",
		"I'm getting ready\nto go to gym tomorrow\nI'm so exhausted",
		"I can't believe I\ngot my nails done today I\nknow what i'm doing",
		"I really wish I\ncould do something with my life\nbut I don't want it",
		"I just wanna know\nwho I am and what I've been\ndoing lately Help",
		"What am I supposed\nto do to live a life that\nI can't live without",
		"Dang I was just\ntrying to impress you guys\nYou're amazing too",
		"It's been a while since\nI've posted anything like\nthis I guess it's cool",
		"I can't wait for\nChristmas to meet and greet my\nfamily again",
		"I wanna go to\na walking marathon but I\ndon't want to go straight",
		"If it doesn't rain\non Sunday I'm gonna be\nfucked again this week",
		"people who don't know\nshit about music will do\nmore harm than good lol",
		"I'm tired of hearing\nabout people who act like\nthey know everything",
		"remember when you\nused to be the one who didn't\nhave to go to sleep",
		"I'm always there for\nyou I'll always be there for\nyou I'm always there",
		"I'm just happy that\nI'm finally happy with\nmy life and I'm done",
		"good morning i have\na special day for you all\nglad to you all",
		"I'm starting to think\nthat he's not capable of\ncreating anything",
		"I really never\nthought we'd be in this relationship\nbut I'm still here now",
		"The older I get\nthe more competitive I\nget in our lives",
		"I'm honestly\nexcited to go to school\nthis November ",
		"I just wanna see\nhow the afternoon goes I\nhave to have the flu",
		"If you're serious\nabout getting rich you have to\nget rich yourself too",
		"We would never use\nyou again because you'll be\nmore than anything",
		"I used to believe\nthe laws I read on the bible\nwere true for real lol",
		"I'm gonna sleep with\na robot and I'm gonna\nbreak my phone again",
		"Feeling like I've blown\nmyself because I feel like\nI'm falling apart",
		"I just wanna go\nout but I really don't want\nto go out anymore",
		"It's the first time the\nday has ever needed\nsomething so fucking cool",
		"Never thought I'd see\na show more broken and sad\nthan this one tonight",
		"I wish I could have\nan Easter egg and I\nwanna get one anyway",
		"I need someone who\nwill stop talking about me\nand stop talking too",
		"I'm thinking about\ngoing to the corporate\nlevel right now lol",
		"I'm so tired of\nthe way you make excuses\nfor your own mistakes",
		"The most important thing\nin this world is to be loved\nand to have someone",
		"I'm really not stressed\nout about anything anymore\nso i'm not upset",
		"i'm just trying to\nmake someone feel like they can\nstay with me forever",
		"I'm so excited\nto start moving out of town\nfor a while it's nice",
		"You can't take a man\nfor granted and think he can\ndo things for you",
		"I'd rather have a\nrelationship with someone\nwho supports me I guess",
		"i'm like an angel\nand i'm such a bad person\nbut i'm okay with it",
		"I'm amazing I\nhope you'll have a wonderful\nyear so far Love you",
		"My baby loves to\ntouch my hair because it gets\nso messy and curly",
		"I'm not exactly\nimpressed by anything in\nthis world I'm just dumb",
		"Can someone tell me I\ndidn't get what i needed\ntoday I'm too busy",
		"I'm not going to\nget tired of being tired\nI'm going to sleep",
		"My brother told me\nthat the people in my life\nare so much better",
		"i would never text\nanyone else but my heart\nis so important",
		"I'm having a hard\ntime falling asleep but I\nstill wanna sleep",
		"I have a feeling\nI'm going to be released\non Monday Thank you",
		"I'm not allowed to\nbe on Facebook anymore\nso I'm dropping it",
		"I'm honestly so\nsick of being the only\none to get sick of it",
		"So sorry I'm not\non Twitter anymore but\nthanks for the follow",
		"the only thing I\nknow is I look like an angel\nand I look like an angel",
		"Tired of the same\nsame thing over and over\nagain every day",
		"I've been faced with so\nmany things that just have no\nway to move forward",
		"I have just known\nmyself for so long and it\njust doesn't feel right",
		"A man who doesn't\nget a hug for breakfast wants\nto be with you all day",
		"You should be writing\nlike a kid who's just trying\nto get attention",
		"I could be crazy\nif I just said I love you\nbut I don't love you",
		"I hate people who\njust question anything I\never say dude",
		"Just because I have\na headache doesn't mean I\nhave to stay with it",
		"I did not deserve\nmy red birthday shirt I hope\nyou can enjoy it",
		"I'm not being dramatic\nI'm saying I'm taking the\nshit out of you guys",
		"It's official I\nam going to watch the new\nManchester derby",
		"So y'all wanna know\nabout all the shit I've been\nthrough in my life",
		"Where do you get those\nvegan food stamps that we\ncan't understand",
		"I'm ready to go\nto work and I'm ready to\ngo to the gym too",
		"I am very jealous\nof all the good people in\nthe world that I love",
		"Passionate and firm\nand true I have never\ncraved the world for my life",
		"when will I ever\nreally stop being so\ndamn cute I love her",
		"If there's only one\nthing I can't get upset about\nis me being mad",
		"I be trying to\nstay positive because a\nbad person is there",
		"I say I'm sorry\nfor the past tense but I'm not\nsorry for the present",
		"I am so happy\nto have you and I hope you\nhave a happy day",
		"I'm so tired of\nbeing on the phone all day\nfor no reason",
		"I would rather fly\nto Japan or China but\nI hate both above",
		"I was about to\ngo out and buy all these clothes\nbut they're too expensive",
		"I am not an adult\nbut I am a person you\nknow how to treat me",
		"You never know how\nsomeone will react to you\nwhen you know they're wrong",
		"I'm about to be\nso weird I think I'm gonna\nhave a panic attack",
		"I've been eating too\nmuch garbage in my life and\nI just need a break",
		"If you have missed out\nI hope you can take a look\nat your account now",
		"I'm trying to be\nastute and witty so I\ncan make my own memes",
		"Wow I wish I was\nalready on a plane to see\nPerry tonight LIVE",
		"When is the next time\nI'm going to get my hair\ndone because it's mad",
		"It's crazy how much\nmy anxiety can turn\ninto sadness lol",
		"I'm so tired of\nthis bullshit and I can't be\na part of it anymore",
		"I'm about to go\nto spend this weekend with my\nfamily and friends",
		"I remember when\nI went to McDonald's\nto get fries and burgers",
		"I'm gonna never\nlearn to enjoy things it's\ntoo much for me LOL",
		"I wish someone would\njust stop messing around\nand do things right",
		"I have a feeling\nJeff's gonna end up being\na legend this week",
		"I'm literally\nscreaming at this point because\nI'm getting too crazy",
		"I got so many\nthings to do and I feel like I\ncan't get out of bed",
		"I'm very scared to\nget up and make it to work\ntoday BUT I CAN",
		"please don't be afraid\nof him and don't even try\nto scare him away",
		"Sorry I didn't\nknow you would do this I hope\nyou didn't do it",
		"I'm just trying to\nget my stuff out to the side\nI'll reflect on it",
		"if you really love\nsomeone you should find a way\nto get to know them",
		"I've been trying to\nget my feelings out of people\nI'm not a perfect person",
		"It's so annoying\nwhen people don't even know\nhow to cook and cook",
		"I'm putting my money\ninto this nowadays and I\ncan't wait to see it",
		"i'm not gonna support\nanyone that doesn't have\na good relationship",
		"Can't believe how much\nI'm enjoying this morning\nI feel so refreshed",
		"I've been doing this\nfor so long that I can't wait\nto give it a try",
		"this is my only\nfeeling when I pass through the\ngoblin tunnel again",
		"I can't believe I\nmade a mistake and it hurts\nso much to see it",
		"Roses are pink white\nred nightingales are blue blue\nand red are white",
		"I wanna go to\na concert or something but it\nisn't gonna happen",
		"I'm just trying to\nmake a difference in the world\nI need to influence",
		"People who hate spoons\nare the worst people in the world\nfor som reason lol",
		"If you cant go to\nthe movies with someone who\nwill not let you down",
		"I can't believe how\nmany people I have lost in\nthis world I feel broken",
		"I have to do a\nmorning workout before my\nmorning workout lol",
		"Life is a journey\nbut you can't walk away if\nyou have to walk away",
		"I'm a fucking idiot\nand I'm not going to let\nthis happen to me",
		"I'm just trying to\nnot pass up some great opportunities\nand good choices",
		"Why do I always\nget anxious when I have a\nlittle stress in me",
		"I'm not gonna let\nanyone hurt me it's my\nlife I have to fight",
		"I don't understand\nwhy I'm a little sad but\nI love her so much",
		"I'm really not a\nfootball fan I really don't think\nyou'll ever play well",
		"Congratulations\nto the best player in the\nleague today Thank you",
		"We need a leader\nwho is willing to push the\natm no matter how",
		"Nothing sweeter than\nthe feeling of being on\nthe road again yo",
		"Finally got my\ntattoos done and I still can't\nkeep my head above",
		"Don't even get me\nstarted on who you're going\nto get hurt with this",
		"Your internet is\ngoing to be shit I need\nto get back to it",
		"I'm gonna go see\nthe first movie this weekend\nI love this movie",
		"I'm sorry I can\njust stop crying and just go\nget something to eat",
		"I'm starting to wonder\nwhy I didn't finish the\nmovie earlier",
		"We are all gonna\nmiss this sunny day and I'm\nso grateful for it",
		"I'm literally\nnot gonna lie I'm not\neven going to sleep",
		"i hear people say\nthey wanna be a weed but\ni already know",
		"i'm really broke do\ni ever lose a friend and\ni can't even scroll",
		"I'm sorry but Im\nnot getting the hint of my\nlife for what I know now",
		"Walking around the\nmall like I'm going back to\nmy old country town",
		"I'm an adult Why\ndo I feel like I'm a child\nLet me explain it",
		"I just wanna know\nhow many times I've been in a\nrelationship lol",
		"Sorry it's Wednesday\nbut you should be writing like\na duck and have a bath",
		"I haven't been in\nhigh school so I guess its a\nconcentration camp",
		"Why are people not\ngonna do the equivalent\nof my job interview",
		"I didn't know that\nthe key to success was to\nmake yourself understand",
		"I'm trying to go\nto work but at the same time\nI'm not doing it",
		"But the only way\nyou'll have a relationship\nis if you smoke pot",
		"I'm just gonna start\nthe fucking day off with my\nbest friend Melanie",
		"I just want someone\nwho will be with me every\nnight and that's it though",
		"i wanna see a\nred herring when i have to\nlive in a dark house",
		"this is the best shit\ni've read in a while and i\nknew you wouldn't like",
		"i've been so wrapped up\nin these lectures i can't even\nthink of words lol",
		"I'm pretty sure I\ngot a bottle of champagne\non my finger now",
		"I'm gonna be out\nof here for the rest of the\ndays and no one knows",
		"I'm ready for my\nFriday prayers I want to\nfeel the peace in you",
		"I'm already a\nsick person I'm ready to\nget back to my life",
		"Well before I\nstart collecting garbage I\nneed to be the boss",
		"You know when you're in\na relationship and you\nfeel like a baby",
		"the police is the\nbest service they've ever had\nbecause they don't care",
		"You could say that all\nthe time and you wouldn't be the\none to say it either",
		"I'm not gonna fix\nthe problem today I'm not\ngoing to fix it",
		"I feel like I'm the\nonly person that doesn't\nknow how to use my phone",
		"As I move on my\njourney there is nothing I\ncan do to stop you",
		"I'm ready to move\nto a new city and you\ncan't take my happiness",
		"You can't see anything\nyou don't want because you\ndon't want to see it",
		"I'm so tired of\ndying I'm so tired of\ngetting this money",
		"i always forget\nwhere i got my money because\ni'm not rich enough",
		"Trying to get a\npicture of myself lol i\nwant to be seen x",
		"I was supposed to\nbe okay but I felt like\nit was killing me",
		"I've been listening\nto all the best songs in hip\nhop for hours",
		"I can't be sorry\nfor being so nice to you\non a Monday night",
		"You can't ever say\nthat you aren't in love with\nthem You just can't",
		"Life's not about you\nit's about the people that\nare with you in life",
		"i'm leaving for grad\nschool then i'm ready to go\nback to my dream home",
		"I'm so happy that\nI'm going to a new\ncity in a week",
		"I'm going to keep\non being a rhythm so\nI can never die",
		"I'm sorry but I\nwas just asking for all these\npeople to be friends",
		"I've never been more\nthankful for my family\nthan I am today",
		"I can't believe I\nhave to go through this again\nI'm so lucky lol",
		"I really need to\nstop smoking weed but I'm not\ntaking any chances",
		"I've been waiting for\nthis all weekend I'm about\nto be in a funk",
		"I think I'm gonna\nget my ass kicked tonight and I'll\nbe in a good mood",
		"i cannot wait to\nsee the time when i'm going\nto see the world again",
		"I could literally\nbe a sparrow with ten tails\nif I didn't cut",
		"I'm not surprised people\ndo not like me because that's\nwhat they expected",
		"I'm pulling my hair\nout now and I need to dye\nit twice a week",
		"cheating on people\nis so much worse than cheating\non yourself sorry",
		"I just wanna know\nif i can go back to the\nactual world",
		"Anyways I'm ready\nto move to the states and get\nmy hair done today",
		"How am I supposed\nto get my nails done when I\nknow nobody else",
		"I haven't been on\nTwitter for a month and I\nstill can't believe it",
		"I will never get\nsick unless I get my nails done\nin Dubai this year",
		"people with super\nstrong opinions are the best\npeople in the world",
		"I'm not going to\ndo this anymore but I'm\nhappy that it's over",
		"I honestly just\nwanna live life like the rest\nof my family",
		"The only reason\nI want to tweet is because\nI wanna see you",
		"I'm just gonna go\nout I'm not gonna lie I\ndon't have a life here",
		"I'll never forget\nhow beautiful my tattoo\nlooks I am so cute",
		"Staring at you while\nyou're in your car makes me feel\nlike I'm falling",
		"I'm having a dream\nof taking a burger and\neating it right now",
		"I hate when people\ntell me that I'm mentally\nuncomfortable",
		"I'm just trying to\nmake a movie so I can\nwatch the second one",
		"Why does everyone\nI've met feel the need to get\nup and go to sleep",
		"I'm not invested\nin having the money to get\ninto a car purchase",
		"Nothing better than\nsomeone being self sufficient\nthat makes you smile",
		"Honestly I just\nwant someone to love me more\nthan anything else",
		"I don't wanna live\nforever but I hope I will\nhave a good time tonight",
		"Why does everyone\nin my class always ask me\nto be their butt lol",
		"I don't know how to\nrespond to people who talk\nabout how great they are",
		"today is gonna\nbe a bad day i can't wait\nto go to the gym",
		"I really wanna\nwatch madagascar but shit\nis getting really wild",
		"the biggest piece of\ncandy I've ever seen is\npressed against my face",
		"My cousins really\nmurdered my co workers and\nthey're in jail for it",
		"I'm sorry if you\nhave any problems with your\nemail or anything",
		"I'm ready to go\nto Taiwan tomorrow\nhave a cool day bye",
		"i was gonna get\na tiny pair of black eyes\nbut i'm not so smart",
		"I really want to\nstop listening to music\nand just focus on",
		"And it's really just\nme wanting people to\nbe like me again",
		"Great story Hope the game\nis over so we can go\nto the green room now",
		"A man who only\nlikes to smoke weed makes me feel\nlike I'm a scum lol",
		"I've just been seeing\na bunch of shitty reviews\nfor the last four months",
		"My heart is going\ncrazy today my whole life\nis going crazy",
		"I just wanna go\nto the gym and get some chili\nbut I need some cold",
		"The last few days have\nbeen the most boring of\nmy life I think",
		"A unicorn is\nalways on the top of the\nviolet sky I swear",
		"Do you ever have\nthe urge to be in a car\nand just drive around",
		"If you had a Year\nin Brazil your life would be\na lot better than",
		"There's no reason why\nyou should be working at the\nsame company as me",
		"seriously I\nneed a new voice I need to\nlearn how to breathe",
		"I've been looking for\nsomeone to take me out on\na date this weekend",
		"I think I'm gonna\ntry this Google Home today\nI'm just a bit scared",
		"Just because it's a\nlittle different doesn't mean\nit's nothing to look at",
		"I really need to\nstop seeing people I don't\nlike on social media",
		"I'm coming to the\nconclusion that certain things are\nnot worth the effort",
		"I'm not a weirdo I\njust maybe have a weird appetite\nfor all kinds of things",
		"Trying to get more\ncreative and start doing\nstuff in the future",
		"I'm the only one\nwho likes doing my makeup\nand my nails I guess",
		"Does anyone else\nhave a car that is super\nexpensive or just me",
		"I'm a truly\nbad person I can't stand the\nway I treat people",
		"I'm trying to get\na new job so I can get\na lot of money",
		"Getting the iPhone\nor the new iPhone X is\na fucking nightmare",
		"just because you're not\nhere doesn't mean that you're not\ncoming back to me",
		"I'm not ready to\nstart working out but I'm ready\nto start working out",
		"I'm still trying to\nunderstand why you guys are\nmaking me feel okay",
		"Going to get some\nnew glasses and then I can\nwear them all weekend",
		"If you are reading\nthis you're probably saying\nthis to yourself",
		"I can't believe I\nonly have one person in my\nlife who can love me",
		"i thought i was\ncool because i got some\npizza and tacos",
		"I wish I could\nbe strong but I don't know how\nI can be strong lol",
		"I'm about to get\npunched in the face on my way\nto the hospital",
		"I'm literally\non my way to London this\nweek to get a coat",
		"I'm a super dumb\nperson But I love you guys\nYou are so sweet to me",
		"I'm going to do\nmy best everyday to get\nthis guys' attention lol",
		"I'm getting a new\ntattoo and I feel like I\nwanna die right now",
		"I'm going to take\na shower and just watch movies\nwith my friends again",
		"very interesting\npeople are talking about\nWhat is going on",
		"I don't understand\nhow people even like me\nI just don't like them",
		"When your heart is broken\nyou don't know what to do or\nhow to move on from it",
		"Can't believe I'm in\nthe process of learning to\nbe an adult again",
		"honestly if you\nfollow me on twitter you\nknow what i mean lol",
		"Why does my phone always\nshutdown when I'm trying to\nfocus on the game",
		"I don't wanna be\na complete asshole anymore\nI'm just good at it",
		"I'm about to try\nto go on a date with a\ndifferent man tonight",
		"You should be writing\nlike a person who can't write\nan alphabet",
		"I don't wanna be\nthe only one who thinks i don't\nneed a promotion lol",
		"I'm a gamer but\nI like to play with my friends\nand I'm just a gamer",
		"I wanna be a\nbeauty queen because I want\nto be a beauty queen",
		"I only want coffee\nand alcohol and I don't\nwant to be with you",
		"I just wanna read\nsomething that reminds me of\nmy mom's book collection",
		"does anyone know of\na good internet channel where\nyou can post messages",
		"I'm really happy\nwith my friends I really have\na good time right now",
		"I can't get over\nhow wonderful it is\nto have someone like you",
		"My favourite thing\nto do is just sit down and\ndrink a Coca Cola",
		"I am always the\none that always gets the best\nbuy and the best deals ",
		"I will always love\nyou forever as long as\nI'm with you always",
		"I really want to\nstart working out I'm NOT\neven a yogi",
		"I'm taking a risk\nand it's up to me to make\nme a better man",
		"I think it's finally\nbeen determined that my nose\nis a faulty one",
		"When people talk shit\nabout you it makes you feel\nso uncomfortable",
		"I'm trying to keep\ntwitter up this week it's my\nsoul and my body lol",
		"Didn't realise\nthis was a monday and i\nlove my day off lol",
		"When you're tired you\ngotta stay focused on the\nthings that keep you alive",
		"Talking about a\nhot topic isn't the same\nas being funny",
		"My friend is becoming\na psychopath I'm gonna get\nmy head checked out soon",
		"I'm sorry but you\nreally don't need to hear anything\nabout your life anymore",
		"I'm not okay with\nthe amount of money I\nhave in my bank account",
		"Just looked at my friend\nand she said I'm into you\nAND I'm into them",
		"I really think that\na picture of the president\nis hilarious",
		"If I become a\nvegan I will be vegan\nwithin the next year",
		"If I only had\na head of lettuce I would\nhave a cheese sandwich",
		"I'm smoking a pipe\nand I'm being sarcastic\nI need to stop that",
		"That's why I'm convinced\nthat Justin Bieber was the\nbest rapper ever",
		"How many times I\nhave to admit that the world\nis going to hell",
		"I swear every\ntime I see something that you\ndon't like I forget it",
		"good morning i love\nyou so much i wish you a\nhappy day today",
		"Lol I'm not saying\nI'm good I just want to\nget a life with you",
		"I want to be a\nrobot and I want to be\na human being",
		"I know my parents\nare joking about me so\nI don't judge them lol",
		"Thank you for helping\nbring the world some peace and joy\nto the world today",
		"drunk on the side of\nthe road and I'm so ready\nto get out of here",
		"I wanna get a\nnew car but I think I'm too\nold to drive now LOL",
		"I've discovered a new\nway to tweet everything I\nimagine you doing",
		"I'm ready to be\nback in the big city\nfor the holidays",
		"I'm not going to\nwatch the whole episode of\nThe Last Jedi again",
		"i'll be honest you\ndo look like a lot of shit\nbut i love you anyway",
		"Nobody is gonna\nlisten to me this time and\nI will continue",
		"Doing everything\nto avoid talking to you\nis the hardest part",
		"I was only here\nto get me a bag of\nluxury clothes for me",
		"I hope this is not\na smoke screen but a smoke\nscreen for a pizza",
		"How are you going\nto write your own essay if\nyou don't know where to start",
		"got a caramel\nand sugar cookie and I'm not\nsad anymore lol",
		"I'm gonna cry because\nI'm so tired of being\nheld up as a hero",
		"I have a feeling\nI'm gonna be living in\na very hot place",
		"When is it okay\nfor people to be weird in\nsocial situations",
		"I can't believe it\nwas my own mom who hit me\nwith a minibus",
		"Should've used a backpack\ninstead of a handbag Why\nI'm so fucking pissed",
		"I'll be the greatest\nplayer ever by the end\nof my career lol",
		"I'm going to try\nto be better again Give\nme hope I can be",
		"I'm actually\ngreat at reading the news and\nreading the stories",
		"I actually\ndon't care about the weather\nI just want to skate",
		"I've been eating some\nof those vegan cheese and\nI'm okay with that",
		"Okay I'm gonna\ntry to find some new sneakers\nfor my dog tomorrow",
		"Today is my last\nday of school I'll be back in\ncustody on Wednesday",
		"the moment when you\ntreat someone as if they are\nin a relationship",
		"I haven't been a\nfan of Facebook in a while\nthis feels like death",
		"There's a magic word\nyou can only find in your\nheart and you can't find ",
		"so many awesome\npeople in discord Thank you\nfor being so great",
		"If you're not buying\nanything I'm selling it\nyou're not buying it",
		"Wanna get me some\nfish tacos and a bottle\nof wine tonight",
		"Damaged little\nwebsites make me feel so sad\nI wanna cry lol",
		"Okay I'm just\nhaving a look at the\ninternet right now",
		"Sitting in the car\nlistening to the radio\nmaking a rage trip"
	]

 exports.getHaiku = () => haikus[Math.floor(Math.random() * haikus.length)]
 